name: calliope_NL
channels:
    - conda-forge
    - gurobi
dependencies:
    - python=3.12
    - gurobi
    - plotly
    - jupyterlab
    - pip
    - pip:
        - git+https://github.com/calliope-project/calliope.git@bdda2dbb7c359ed8dfc38b51b884b1bbb837a464